# ECE399 Winter 2017
# Aaron Chan
#
# Makefile for Assignment 1 programs
# Programs: header, timer, piper, signaler

all: header timer piper signaler

header: header.c
	gcc -g -o header header.c

timer: timer.c
	gcc -g -o timer timer.c

piper: piper.c
	gcc -g -o piper piper.c

signaler: signaler.c
	gcc -g -o signaler signaler.c
