# Aaron Chan
# Assignment 3 - Shell Program
# ECE399 Winter 2017
# Makefile

all: shell

shell: shell.c read_parse.c custom_exe.c pipe_direct.c header.h
	gcc -g -Wall -o shell shell.c read_parse.c custom_exe.c pipe_direct.c

