# Aaron Chan
# ECE399 Winter 2017
# Assignment 5
#
# Program to sort an array of integers

all: threading

threading: threading.c sorting.c
	gcc -Wall -pthread -o threading threading.c sorting.c header.h
